# Generated by Django 4.1.3 on 2022-11-19 17:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kalam', '0002_qac_qa_question_comment_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qac',
            name='publishDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 17, 53, 54, 926747)),
        ),
        migrations.CreateModel(
            name='UserVotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voteType', models.BooleanField()),
                ('_QAC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalam.qac')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalam.user')),
            ],
            options={
                'unique_together': {('user', '_QAC', 'voteType')},
            },
        ),
    ]