# Generated by Django 4.1.3 on 2022-11-23 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalam', '0003_alter_qac_publishdate_uservotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qac',
            name='publishDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 2, 53, 39, 581841)),
        ),
    ]