# Generated by Django 4.1.3 on 2022-11-24 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalam', '0006_alter_qac_publishdate_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qac',
            name='publishDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 24, 9, 33, 30, 325941)),
        ),
    ]
